from .io_utils import list_to_dict, load_records
from .text_utils import parse_word_list


def select_examples(path, ids=None):
    examples = load_records(path)
    if not ids:
        return examples
    by_id = list_to_dict(examples)
    return [by_id[str(example_id)] for example_id in ids]


def build_topic_icl(examples, text_field="llm_gen_text", topic_field="topic_sent"):
    prompts = []
    for ex in examples:
        topic = ex.get(topic_field)
        if topic is None and ex.get("top2_sents"):
            topic = ex["top2_sents"][0]
        if topic is None:
            raise KeyError(f"Example {ex.get('id', '')} has neither `{topic_field}` nor `top2_sents`.")
        prompts.append(f'Text:"{ex[text_field]}"\nTopic sentence:"{topic}"\n\n')
    return "".join(prompts)


def build_draft_icl(examples, text_field="llm_gen_text", prompt_field="instruction"):
    return "".join(f'LLM-Generated Text: "{ex[text_field]}"\nPrompt: "{ex[prompt_field]}"\n\n' for ex in examples)


def build_final_icl(examples):
    header = "Given the following text generated by a language model and the draft prompt, please improve the prompt based on the hint or noise.\n\n"
    body = []
    for ex in examples:
        hints = ex.get("top_words", [])
        if not isinstance(hints, list):
            hints = parse_word_list(hints)
        noises = parse_word_list(ex.get("removewords", []))
        body.append(
            'Outputs: "{0}"\nDraft: "{1}"\nHint: "{2}"\nNoise: "{3}"\nRecovered prompt: "{4}"\n\n'.format(
                ex["llm_gen_text"],
                ex.get("reconstruct_instruction", ex.get("draftprompt", "")),
                ",".join(hints),
                '","'.join(noises),
                ex["instruction"],
            )
        )
    return header + "".join(body)
